export const ORDER_STATUS_MAP = {
    CREATED: 'CREATED',
    PAID: 'PAID',
    PAYMENT_ERROR: 'PAYMENT_ERROR',
    TO_DELIVERY: 'TO_DELIVERY',
    IN_DELIVERY: 'IN_DELIVERY',
    DELIVERED: 'DELIVERED',
    RECEIVED: 'RECEIVED',
    CANCELED: 'CANCELED',
} as const;
