version: '3.7'

services:
    nginx:
        image: cr.yandex/crpkimrjqc5g9hklf1c2/tridva-nginx-front
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /etc/letsencrypt/live/tridva.store/fullchain.pem:/etc/letsencrypt/live/tridva.store/fullchain.pem
            - /etc/letsencrypt/live/tridva.store/privkey.pem:/etc/letsencrypt/live/tridva.store/privkey.pem
            - /etc/letsencrypt/live/default/fullchain.pem:/etc/letsencrypt/live/default/fullchain.pem
            - /etc/letsencrypt/live/default/privkey.pem:/etc/letsencrypt/live/default/privkey.pem
            - shared-volume:/var/tmp/shared-docker
            - ./log/nginx:/var/log/nginx
        restart: always
        depends_on:
            - frontend

    frontend:
        image: cr.yandex/crpkimrjqc5g9hklf1c2/tridva-front
        volumes:
            - /usr/app/.next/cache/images:/var/tmp/next-images
        restart: always

    backend:
        image: cr.yandex/crpkimrjqc5g9hklf1c2/tridva-api
        volumes:
            - shared-volume:/var/tmp/shared-docker
        restart: always

volumes:
    shared-volume:
