version: '3.7'

services:
    nginx:
        image: cr.yandex/crpkimrjqc5g9hklf1c2/tridva-nginx-front
        container_name: modseccrs
        environment:
            MODSEC_AUDIT_LOG: /var/log/modsec/audit.log
            MODSEC_DEBUG_LOG: /var/log/modsec/debug.log
            SSL_CERT: /etc/letsencrypt/live/tridva.store/fullchain.pem
            SSL_CERT_KEY: /etc/letsencrypt/live/tridva.store/privkey.pem
            MANUAL_MODE: 1
        ports:
            - '80:8080'
            - '443:8443'
        volumes:
            - /etc/letsencrypt/live/tridva.store/fullchain.pem:/etc/letsencrypt/live/tridva.store/fullchain.pem
            - /etc/letsencrypt/live/tridva.store/privkey.pem:/etc/letsencrypt/live/tridva.store/privkey.pem
            - /etc/letsencrypt/live/default/fullchain.pem:/etc/letsencrypt/live/default/fullchain.pem
            - /etc/letsencrypt/live/default/privkey.pem:/etc/letsencrypt/live/default/privkey.pem
            - shared-volume:/var/tmp/shared-docker
            - ~/log/nginx:/var/log/nginx
            - ~/log/modsec:/var/log/modsec
        restart: always
        depends_on:
            - frontend

    frontend:
        image: cr.yandex/crpkimrjqc5g9hklf1c2/tridva-front
        volumes:
            - next-images:/var/tmp/next-images
        restart: always

    backend:
        image: cr.yandex/crpkimrjqc5g9hklf1c2/tridva-api
        volumes:
            - shared-volume:/var/tmp/shared-docker
        restart: always

volumes:
    shared-volume:
    next-images:
