version: '3.7'

services:
    nginx:
        image: cr.yandex/crpkimrjqc5g9hklf1c2/tridva-nginx-front
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /home/ilnarik/cert.pem:/home/ilnarik/cert.pem
            - /home/ilnarik/key.pem:/home/ilnarik/key.pem
            - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
            - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
        restart: always
        depends_on:
            - frontend

    frontend:
        image: cr.yandex/crpkimrjqc5g9hklf1c2/tridva-front
        volumes:
            - /usr/app/.next/cache/images:/var/tmp/next-images
        restart: always

    backend:
        image: cr.yandex/crpkimrjqc5g9hklf1c2/tridva-api
        restart: always
