export {default as search} from './search.svg';
export {default as star} from './star.svg';
export {default as message} from './message.svg';
export {default as hanger} from './hanger.svg';
export {default as chevron} from './chevron-right.svg';
export {default as switch} from './arrow-switch.svg';
export {default as audio} from './audio-settings.svg';
export {default as delivery} from './delivery.svg';
export {default as crown} from './crown.svg';
export {default as help} from './help.svg';

export {default as home} from './home.svg';
export {default as homeActive} from './home-active.svg';
export {default as menu} from './menu.svg';
export {default as menuActive} from './menu-active.svg';
export {default as cart} from './cart.svg';
export {default as cartActive} from './cart-active.svg';
export {default as user} from './user.svg';
export {default as userActive} from './user-active.svg';
