export { default as search } from './search.svg';
export { default as star } from './star.svg';
export { default as message } from './message.svg';
export { default as home } from './home.svg';
export { default as user } from './user.svg';
export { default as menu } from './menu.svg';
export { default as cart } from './cart.svg';
export { default as hanger } from './hanger.svg';
export { default as chevron } from './chevron-right.svg';