name: Nginx deployment

on:
    push:
        branches: ['main']
        paths: ['configs/nginx/**', 'configs/yc/**']
    workflow_dispatch:
        inputs:
            reason:
                description: 'why'
                required: false
                default: 'just for fun'

env:
    NGINX_IMAGE: cr.yandex/crpkimrjqc5g9hklf1c2/tridva-nginx-front

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Dockerhub
              uses: docker/login-action@v3
              with:
                  registry: cr.yandex
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Nginx for together composing
              uses: docker/build-push-action@v5
              with:
                  context: ./configs/nginx
                  file: ./configs/nginx/Dockerfile
                  push: true
                  tags: ${{ env.NGINX_IMAGE }}

    update-yc:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Copy docker-compose
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.YC_HOST }}
                  username: ${{ secrets.YC_USERNAME }}
                  key: ${{ secrets.ID_RSA }}
                  source: 'configs/yc/*'
                  target: '~/frontend'

            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.YC_HOST }}
                  username: ${{ secrets.YC_USERNAME }}
                  key: ${{ secrets.ID_RSA }}
                  script: |
                      cd ~/frontend && 
                      docker compose -f configs/yc/docker-compose.yaml stop && 
                      docker compose -f configs/yc/docker-compose.yaml pull && 
                      docker compose -f configs/yc/docker-compose.yaml up -d &&
                      docker system prune -f
